@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v1
@api_key = {{$dotenv API_KEY}}

### Bienvenida
GET {{root}}

### Autoridades
GET {{baseUrl}}/autoridades
X-Api-Key: {{api_key}}

### Distritos
GET {{baseUrl}}/distritos
X-Api-Key: {{api_key}}

### Domicilios
GET {{baseUrl}}/domicilios
X-Api-Key: {{api_key}}

### Materias
GET {{baseUrl}}/materias
X-Api-Key: {{api_key}}

### Materias Tipos de Juicios
GET {{baseUrl}}/materias_tipos_juicios
X-Api-Key: {{api_key}}

### Oficinas
GET {{baseUrl}}/oficinas
X-Api-Key: {{api_key}}
