@root = http://{{$dotenv HOST}}:{{$dotenv PORT}}
@baseUrl = {{root}}/v1
@username = {{$dotenv USERNAME}}
@password = {{$dotenv PASSWORD}}

### Bienvenida
GET {{root}}

### Autorizacion
# @name auth
POST {{root}}/token
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### Materias
GET {{baseUrl}}/materias
Authorization: Bearer {{auth.response.body.access_token}}

### Distritos
GET {{baseUrl}}/distritos
Authorization: Bearer {{auth.response.body.access_token}}

### Autoridades
GET {{baseUrl}}/autoridades
    ?offset=0
    &limit=10
Authorization: Bearer {{auth.response.body.access_token}}
