@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v1
@api_key = {{$dotenv API_KEY}}

### Bienvenida
GET {{root}}

### Categorias
GET {{baseUrl}}/inv_categorias
X-Api-Key: {{api_key}}

### Componentes
GET {{baseUrl}}/inv_componentes
X-Api-Key: {{api_key}}

### Custodias
GET {{baseUrl}}/inv_custodias
X-Api-Key: {{api_key}}

### Equipos
GET {{baseUrl}}/inv_equipos
X-Api-Key: {{api_key}}

### Marcas
GET {{baseUrl}}/inv_marcas
X-Api-Key: {{api_key}}

### Modelos
GET {{baseUrl}}/inv_modelos
X-Api-Key: {{api_key}}

### Redes
GET {{baseUrl}}/inv_redes
X-Api-Key: {{api_key}}
