@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v1
@api_key = {{$dotenv API_KEY}}

### Bienvenida
GET {{root}}

### Modulos
GET {{baseUrl}}/modulos
X-Api-Key: {{api_key}}

### Permisos
GET {{baseUrl}}/permisos
X-Api-Key: {{api_key}}

### Roles
GET {{baseUrl}}/roles
X-Api-Key: {{api_key}}

### Rol 1 ADMINISTRADOR
GET {{baseUrl}}/roles/1
X-Api-Key: {{api_key}}

### Rol 4 JUZGADO PRIMERA INSTANCIA
GET {{baseUrl}}/roles/4
X-Api-Key: {{api_key}}

### Usuarios
GET {{baseUrl}}/usuarios
X-Api-Key: {{api_key}}

### Usuarios-Roles
GET {{baseUrl}}/usuarios_roles
X-Api-Key: {{api_key}}
