name: Google Cloud App Engine deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "authenticate"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_KEY }}
      - name: "deploy"
        uses: "google-github-actions/deploy-appengine@v1"
        with:
          deliverables: "app.yaml"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
