name: Google Cloud App Engine deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    steps:
      - name: "Authenticate with Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          service_account: ${{ secrets.GCP_SA_KEY }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - name: "Deploy to Google Cloud App Engine"
        uses: "google-github-actions/deploy-appengine@v1"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
